name: Main branch PR

on:
  pull_request:
    branches: [ "main" ]

env:
  DATABRICKS_HOST: ${{secrets.DATABRICKS_HOST}}
  DATABRICKS_TOKEN: ${{secrets.DATABRICKS_TOKEN}}

jobs:

  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Databricks CLI
      uses: databricks/setup-cli@main

      # Databricks CLI can also be installed from main repo
      #run: |
      #  curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
    - name: Test with pytest
      run: |
        pip install pytest pytest-cov
        pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
